### ISSUE TITLE
Warrior - issue & Dunfell takes longer time to generate SPDX

### ISSUE THREAD

**Issue by chaithubk** [fossology/fossdriver#29]
I am planning to use `meta-spdxscanner` layer to generate the SPDX docs in my poky `warrior `distro. I have run the `fossology/fossology:3.5.0 `docker image and have installed `fossdriver`. I am noticing this error with do_spdx() 
```

ERROR: linux-libc-headers-5.0-r0 do_spdx: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_spdx(d)
     0003:
File: '/home/yocto/output/poky_warrior/poky/meta-spdxscanner/classes/fossdriver-host.bbclass', lineno: 137, function: do_spdx
     0133:    bb.note(' run fossdriver ...... ')
     0134:    if not os.path.isfile(tar_name):
     0135:        bb.warn(info['pn'] + "has no source, do nothing")
     0136:        return
 *** 0137:    invoke_fossdriver(tar_name,sstatefile)
     0138:    if get_cached_spdx(sstatefile) != None:
     0139:        write_cached_spdx( info,sstatefile,cur_ver_code )
     0140:        ## CREATE MANIFEST(write to outfile )
     0141:        create_manifest(info,sstatefile)
File: '/home/yocto/output/poky_warrior/poky/meta-spdxscanner/classes/fossdriver-host.bbclass', lineno: 237, function: invoke_fossdriver
     0233:    if (Reuse(server, tar_file, "Software Repository", tar_file, "Software Repository").run()  != True):
     0234:        bb.note("This OSS has not been scanned. So upload it to fossology server.")
     0235:        i = 0
     0236:        while i < 5:
 *** 0237:            if (Upload(server, tar_file, "Software Repository").run() != True):
     0238:                bb.warn("%s Upload failed, try again!" %  tar_file)
     0239:                time.sleep(delaytime)
     0240:                i += 1
     0241:            else:
File: '/home/fossdriver/fossdriver/tasks.py', lineno: 73, function: run
     0069:        logging.info("Upload complete, {} upload ID number is {}".format(self.filePath, newUploadNum))
     0070:
     0071:        # and wait until upload finishes unpacking
     0072:        logging.info("Waiting for upload {} to unpack".format(newUploadNum))
 *** 0073:        self.server.WaitUntilAgentIsDone(newUploadNum, "ununpack", pollSeconds=5)
     0074:        self.server.WaitUntilAgentIsDone(newUploadNum, "adj2nest", pollSeconds=5)
     0075:
     0076:        return True
     0077:
File: '/home/fossdriver/fossdriver/server.py', lineno: 457, function: WaitUntilAgentIsDone
     0453:            - agent: name of agent to check for.
     0454:            - pollSeconds: number of seconds to wait between polling. Defaults to 10.
     0455:        """
     0456:        # FIXME consider adding a max # of tries before returning
 *** 0457:        jobNum = self._getMostRecentAgentJobNum(uploadNum, agent)
     0458:        while not self._isJobDoneYet(jobNum):
     0459:            time.sleep(pollSeconds)
File: '/home/fossdriver/fossdriver/server.py', lineno: 297, function: _getMostRecentAgentJobNum
     0293:            - agent: name of agent to check for.
     0294:        Returns job ID number or -1 if not found.
     0295:        """
     0296:        # FIXME given _getJobsForUpload, currently retrieves just first page
 *** 0297:        jobs = self._getJobsForUpload(uploadNum)
     0298:        if jobs is None or jobs == []:
     0299:            return -1
     0300:        # will be returned in reverse chrono order, so we can just loop through
     0301:        # and stop on the first one we come to
File: '/home/fossdriver/fossdriver/server.py', lineno: 280, function: _getJobsForUpload
     0276:        # response format changed from XML to JSON on or around 3.5.0
     0277:        # see https://github.com/fossology/fossdriver/issues/17
     0278:        if self.IsAtLeastVersion("3.5.0"):
     0279:            # parse json
 *** 0280:            jobData = fossdriver.parser.parseJSONShowJobsData(results.content)
     0281:            return jobData
     0282:        else:
     0283:            # decode and parse XML
     0284:            decodedContent = fossdriver.parser.decodeAjaxShowJobsData(results.content)
File: '/home/fossdriver/fossdriver/parser.py', lineno: 209, function: parseJSONShowJobsData
     0205:    jobData = []
     0206:    js = json.loads(content.decode('utf-8'))
     0207:    showJobsData = js.get("showJobsData", [])
     0208:    for sjd in showJobsData:
 *** 0209:        jd = sjd.get("job", None)
     0210:        if jd is not None:
     0211:            jq = jd.get("jobQueue", None)
     0212:            if jq is not None:
     0213:                for k, v in jq.items():
Exception: AttributeError: 'str' object has no attribute 'get'

ERROR: linux-libc-headers-5.0-r0 do_spdx: 'str' object has no attribute 'get'
ERROR: linux-libc-headers-5.0-r0 do_spdx: Function failed: do_spdx
ERROR: Logfile of failure stored in: /home/yocto/output/poky_warrior/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/linux-libc-headers/5.0-r0/temp/log.do_spdx.27653
ERROR: Task (/home/yocto/output/poky_warrior/poky/meta/recipes-kernel/linux-libc-headers/linux-libc-headers_5.0.bb:do_spdx) failed with exit code '1'

```

Can you please help me to solve this. ?

**Comment by chaithubk** [comment]
To just make sure it's not due to old docker version & Warrior branch. I have tried the same on the Dunfell branch. Atleast, I see that there are no errors but the build was stuck in the do_spdx stage for a quite long time (bitbake configuration below) 
```
Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "qemuarm"
DISTRO               = "poky"
DISTRO_VERSION       = "3.1"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "dunfell:a44b8d2856a937ca3991cbf566788b0cd541d777"
meta-oe              
meta-python          = "dunfell:e413c1ef621688e69bb7830bb3151ed23b30b73e"
meta-spdxscanner     = "master:c731a5f1cc83d9d8a1e120207746c89059d5576f"

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:10
Sstate summary: Wanted 1526 Found 12 Missed 1514 Current 1065 (0% match, 41% complete)
NOTE: Executing Tasks
WARNING: linux-libc-headers-5.4-r0 do_spdx: Creating /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/linux-libc-headers/5.4-r0/spdx_sstate_dir/arm-poky-linux-gnueabi/linux-libc-headers-5.4-r0/linux-libc-headers-5.4-r0-patched.tar.gz
Currently  1 running tasks (444 of 6684)   6% |##########                                                                                                                                                  |
0: linux-libc-headers-5.4-r0 do_spdx - 37m28s (pid 10172)
```
And I see the below errors in the fossology server running locally via docker run. 

```
[Sat Jun 06 10:30:43.160030 2020] [:error] [pid 237] [client 172.17.0.1:48222] PHP Fatal error:  Uncaught InvalidArgumentException: Cannot redirect to an empty URL. in /usr/local/share/fossology/vendor/symfony/http-foundation/RedirectResponse.php:86\nStack trace:\n#0 /usr/local/share/fossology/vendor/symfony/http-foundation/RedirectResponse.php(39): Symfony\\Component\\HttpFoundation\\RedirectResponse->setTargetUrl('')\n#1 /usr/local/share/fossology/www/ui/core-auth.php(219): Symfony\\Component\\HttpFoundation\\RedirectResponse->__construct('')\n#2 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(381): core_auth->Output()\n#3 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(465): FO_Plugin->getResponse()\n#4 /usr/local/share/fossology/www/ui/index.php(64): FO_Plugin->execute()\n#5 {main}\n  thrown in /usr/local/share/fossology/vendor/symfony/http-foundation/RedirectResponse.php on line 86
172.17.0.1 - - [06/Jun/2020:10:30:43 +0000] "POST /repo/?mod=auth HTTP/1.1" 500 2588 "-" "python-requests/2.20.0"
172.17.0.1 - - [06/Jun/2020:10:30:43 +0000] "GET /repo/ HTTP/1.1" 200 4820 "-" "python-requests/2.20.0"
172.17.0.1 - - [06/Jun/2020:10:30:43 +0000] "GET /repo/?mod=upload_file HTTP/1.1" 200 6483 "-" "python-requests/2.20.0"
[2020-06-06 10:30:44] Fossology\Lib\Util\DataTablesUtility.WARNING: did not find iSortingCols in inputArray [] []
172.17.0.1 - - [06/Jun/2020:10:30:43 +0000] "GET /repo/?mod=browse-processPost&folder=1&iDisplayStart=0&iDisplayLength=100 HTTP/1.1" 200 351 "-" "python-requests/2.20.0"
172.17.0.1 - - [06/Jun/2020:10:30:44 +0000] "GET /repo/?mod=upload_file HTTP/1.1" 200 6486 "-" "python-requests/2.20.0"
172.17.0.1 - - [06/Jun/2020:10:30:44 +0000] "GET /repo/?mod=upload_file HTTP/1.1" 200 6474 "-" "python-requests/2.20.0"
172.17.0.1 - - [06/Jun/2020:10:30:44 +0000] "POST /repo/?mod=upload_file HTTP/1.1" 200 6717 "http://127.0.0.1:8081/repo/?mod=upload_file" "python-requests/2.20.0"
172.17.0.1 - - [06/Jun/2020:10:30:58 +0000] "POST /repo/?mod=ajaxShowJobs&do=showjb HTTP/1.1" 200 1409 "-" "python-requests/2.20.0"
[Sat Jun 06 10:30:59.194572 2020] [:error] [pid 239] [client 172.17.0.1:48228] PHP Notice:  Undefined index: sEcho in /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php on line 202
172.17.0.1 - - [06/Jun/2020:10:30:58 +0000] "GET /repo/?mod=ajaxShowJobs&do=showSingleJob&jobId=2 HTTP/1.1" 200 1293 "-" "python-requests/2.20.0"
```
Every 10 secs I see this error below on the fossology server:

```
[Sat Jun 06 11:09:03.183260 2020] [:error] [pid 179] [client 172.17.0.1:50422] PHP Notice:  Undefined index: sEcho in /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php on line 202
172.17.0.1 - - [06/Jun/2020:11:09:03 +0000] "GET /repo/?mod=ajaxShowJobs&do=showSingleJob&jobId=4 HTTP/1.1" 200 26095 "-" "python-requests/2.20.0"

```
**And the do_spdx build time keeps increasing.** 

I do have the fossdriver installed (shown below)

```
pip3 list
...
fossdriver (0.0.3, /home/fossdriver)
...
```
Am I doing the configuration correctly. ?

**Comment by swinslow** [comment]
Hi @chaithubk, thanks for filing this issue.

It looks like there's a few different components you're using here: meta-spdxscanner, Fossology, and fossdriver. Adding @leimaohui and @mcjaeger in case they have thoughts here as well (or know who else in the community might be able to weigh in).

For the problem you noted in your initial issue, that might relate to a change that happened in Fossology's output on or around the 3.5.0 version (see #17). I believe we had fixed this in #21, but if you are still seeing problems then we might need to take a closer look. I don't have a 3.5.0 Fossology server currently set up to test.

However, it sounds like you may have been able to resolve that situation at least by switching to the Yocto Dunfell release. I see then that you're now getting the following error:

```
[Sat Jun 06 11:09:03.183260 2020] [:error] [pid 179] [client 172.17.0.1:50422] PHP Notice:  Undefined index: sEcho in /usr/local/share/fossology/www/ui/async/AjaxShowJobs.php on line 202
172.17.0.1 - - [06/Jun/2020:11:09:03 +0000] "GET /repo/?mod=ajaxShowJobs&do=showSingleJob&jobId=4 HTTP/1.1" 200 26095 "-" "python-requests/2.20.0"
```

@mcjaeger, this looks like an error on the Fossology side -- do you have any idea what might cause this, or who from the Fossology community could take a look at it?

**Comment by chaithubk** [comment]
Hi @swinslow Thank you. 
Yes, now with `Yocto Dunfell` and `fossology/fosslogy:latest` I see some files getting generated now as below: 
```
/spdx-outdir-dunfell$ ls
linux-libc-headers-5.4.spdx
```
But the issue is I still see the above mentioned errors on the fossology side. And each package is taking a very large amount of time in `do_spdx()` stage, for example the `glibc` below has been running from almost ~5 hours. 

```
NOTE: Executing Tasks
WARNING: scancode-toolkit-native-3.1.1-r0 do_populate_sysroot: File '/home/yocto/output/build/tmp/work/x86_64-linux/scancode-toolkit-native/3.1.1-r0/recipe-sysroot-native/usr/bin/bin/python3' from scancode-toolkit-native was already stripped, this will prevent future debugging!
Currently  1 running tasks (522 of 6695)   7% |############                                                                                                                                                |
0: glibc-2.31+gitAUTOINC+71f2b249a2-r0 do_spdx - 3h18m25s (pid 2302)
```

Is this behavior expected ? I can't see any progress. 
If each package takes this amount time then it's a significant build time generating spdx right ?

**Comment by leimaohui** [comment]
Yes, It spends a lot of time to get spdx file for some huge OSS(e.g. kernel, glibc, qt5). But it's a little too slow to spend 5 hours to get spdx file of glibc. 
Do you know the time it takes that get spdx file from fossology server manually? I mean from upload the source code to download the spdx file.

Besides, if you run multi task of do_spdx, the time for one OSS will be more.

**Comment by chaithubk** [comment]
@leimaohui Thanks for responding. 
I have not tried uploading source manually. I have not really gone through the `Fossology `in detail I have followed your presentation` "How-to-reduce-on-your-OSS-compliance-work"` and configured the system accordingly. I am running my Ubuntu in a `VirtualBox `and after two days of continuous scan I have got `~94 SPDX docs` for the `Dunfell core-image-sato `packages:
```

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:09
Sstate summary: Wanted 1501 Found 0 Missed 1501 Current 1093 (0% match, 42% complete)
NOTE: Executing Tasks
WARNING: glibc-2.31+gitAUTOINC+71f2b249a2-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/glibc/2.31+gitAUTOINC+71f2b249a2-r0/spdx_temp/
WARNING: zlib-1.2.11-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/zlib/1.2.11-r0/spdx_temp/
WARNING: opkg-utils-0.4.2-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/opkg-utils/0.4.2-r0/spdx_temp/
WARNING: bzip2-1.0.8-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/bzip2/1.0.8-r0/spdx_temp/
WARNING: libxcrypt-4.4.15-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/libxcrypt/4.4.15-r0/spdx_temp/
WARNING: ncurses-6.2-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/ncurses/6.2-r0/spdx_temp/
WARNING: bash-completion-2.10-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/bash-completion/2.10-r0/spdx_temp/
WARNING: libcap-ng-0.7.10-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/libcap-ng/0.7.10-r0/spdx_temp/
WARNING: util-linux-2.35.1-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/util-linux/2.35.1-r0/spdx_temp/
WARNING: gdbm-1.18.1-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdbm/1.18.1-r0/spdx_temp/
WARNING: openssl-1.1.1f-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/openssl/1.1.1f-r0/spdx_temp/
WARNING: libtirpc-1.2.5-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/libtirpc/1.2.5-r0/spdx_temp/
WARNING: libffi-3.3-r0 do_spdx: source dir = /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/libffi/3.3-r0/spdx_temp/

....
....
....
```
And like you said, the kernel takes almost a day. 
```
Currently  1 running tasks (2207 of 6695)  32% |###################################################                                   |
0: linux-yocto-5.4.27+gitAUTOINC+bee554e595_ab849248b4-r0 do_spdx - 19h56m33s (pid 14694)
```


**Hopefully, I suppose that the incremental core-image-sato builds won't not take this much time if one of my packages get a patch or something.** 

@swinslow @leimaohui: If I want to understand what is happening on the Fossology side (behind the scenes to generate SPDX), and how to use Fossology server via the web. Is there a good reference that I can refer. ?

**Comment by leimaohui** [comment]
You can reference to https://www.fossology.org/. And because you setup your fossology server by docker, maybe https://hub.docker.com/r/fossology/fossology/ is useful for you.

**Comment by chaithubk** [comment]
@leimaohui  I am able to successfully generate the SPDX docs for all dunfell core-image-sato packages except the below (one is at do_compile, but others failed at do_spdx). 

```
Summary: 5 tasks failed:
  /home/yocto/output/poky/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.40.0.bb:do_compile
  /home/yocto/output/poky/meta/recipes-core/gettext/gettext_0.20.1.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-support/gnutls/gnutls_3.6.12.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-support/libpsl/libpsl_0.21.0.bb:do_spdx
  /home/yocto/output/poky/meta/recipes-gnome/gnome/adwaita-icon-theme_3.34.3.bb:do_spdx
```
The error log for the above failures are below: 

```
ERROR: gdk-pixbuf-2.40.0-r0 do_compile: Execution of '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/temp/run.do_compile.5144' failed with exit code 1:
[1/2] /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
FAILED: docs/gdk-pixbuf-csource.1 
/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
ninja: build stopped: subcommand failed.
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/temp/log.do_compile.5144
Log data follows:
| DEBUG: Executing shell function do_compile
| [1/2] /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| FAILED: docs/gdk-pixbuf-csource.1
| /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
| cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/temp/run.do_compile.5144' failed with exit code 1:
| [1/2] /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| FAILED: docs/gdk-pixbuf-csource.1
| /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gdk-pixbuf/2.40.0-r0/recipe-sysroot-native/usr/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam man.authors.section.enabled 0 --stringparam man.copyright.section.enabled 0 -o docs/gdk-pixbuf-csource.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../gdk-pixbuf-2.40.0/docs/gdk-pixbuf-csource.xml
| I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
| cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home/yocto/output/poky/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.40.0.bb:do_compile) failed with exit code '1'

-----------------------------------------------------------------------------------------------

ERROR: gettext-0.20.1-r0 do_spdx: Could not invoke scancode Command '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/recipe-sysroot-native/usr/bin/scancode -lpci --spdx-tv /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/spdx_sstate_dir/arm-poky-linux-gnueabi/gettext-0.20.1-r0/gettext-0.20.1.spdx /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/spdx_temp/' returned 1:
b'Setup plugins...\nCollect file inventory...\nScan files for: info, licenses, copyrights, packages with 1 process(es)...\nScanning done.\nSome files failed to scan properly:\nPath: spdx_temp/gettext-0.20.1/gettext-tools/misc/archive.dir.tar\nSummary:        info, licenses, copyrights, packages with 1 process(es)\nErrors count:   1\nScan Speed:     0.67 files/sec. 12.99 KB/sec.\nInitial counts: 6072 resource(s): 5835 file(s) and 237 directorie(s) \nFinal counts:   6072 resource(s): 5835 file(s) and 237 directorie(s) for 110.01 MB\nTimings:\n  scan_start: 2020-06-09T135951.126968\n  scan_end:   2020-06-09T162428.611805\n  setup_scan:licenses: 1.30s\n  setup: 1.30s\n  inventory: 1.93s\n  scan:packages: 0.49s\n  scan: 8672.24s\n  output:spdx-tv: 6.64s\n  output: 6.64s\n  total: 8684.54s\nRemoving temporary files...done.\n'
ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gettext/0.20.1-r0/temp/log.do_spdx.6774
ERROR: Task (/home/yocto/output/poky/meta/recipes-core/gettext/gettext_0.20.1.bb:do_spdx) failed with exit code '1'

-----------------------------------------------------------------------------------------------

ERROR: gnutls-3.6.12-r0 do_spdx: Could not invoke scancode Command '/home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/recipe-sysroot-native/usr/bin/scancode -lpci --spdx-tv /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/spdx_sstate_dir/arm-poky-linux-gnueabi/gnutls-3.6.12-r0/gnutls-3.6.12.spdx /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/spdx_temp/' returned 1:
b'Setup plugins...\nCollect file inventory...\nScan files for: info, licenses, copyrights, packages with 1 process(es)...\nScanning done.\nSome files failed to scan properly:\nPath: spdx_temp/gnutls-3.6.12/tests/data/long.pem\nSummary:        info, licenses, copyrights, packages with 1 process(es)\nErrors count:   1\nScan Speed:     1.47 files/sec. 10.75 KB/sec.\nInitial counts: 6564 resource(s): 6456 file(s) and 108 directorie(s) \nFinal counts:   6564 resource(s): 6456 file(s) and 108 directorie(s) for 46.03 MB\nTimings:\n  scan_start: 2020-06-09T171835.506413\n  scan_end:   2020-06-09T183145.722364\n  setup_scan:licenses: 1.17s\n  setup: 1.17s\n  inventory: 1.88s\n  scan:packages: 0.52s\n  scan: 4384.91s\n  output:spdx-tv: 6.71s\n  output: 6.71s\n  total: 4397.42s\nRemoving temporary files...done.\n'
ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/gnutls/3.6.12-r0/temp/log.do_spdx.30861
ERROR: Task (/home/yocto/output/poky/meta/recipes-support/gnutls/gnutls_3.6.12.bb:do_spdx) failed with exit code '1'

-------------------------------------------------------------------------------------------------

ERROR: libpsl-0.21.0-r0 do_spdx: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_spdx(d)
     0003:
File: '/home/yocto/output/poky/meta-spdxscanner/classes/scancode-tk.bbclass', lineno: 110, function: do_spdx
     0106:    if os.path.exists(git_path):
     0107:        remove_dir_tree(git_path)
     0108:    invoke_scancode(info['sourcedir'],sstatefile)
     0109:    bb.warn("source dir = " + info['sourcedir'])
 *** 0110:    if get_cached_spdx(sstatefile) != None:
     0111:        write_cached_spdx( info,sstatefile,cur_ver_code )
     0112:        ## CREATE MANIFEST(write to outfile )
     0113:        create_manifest(info,sstatefile)
     0114:    else:
File: '/home/yocto/output/poky/meta-spdxscanner/classes/spdx-common.bbclass', lineno: 164, function: get_cached_spdx
     0160:    except subprocess.CalledProcessError as e:
     0161:        bb.error("Index creation command '%s' failed with return code %d:\n%s" % (e.cmd, e.returncode, e.output))
     0162:        return None
     0163:    cached_spdx_info=output.decode('utf-8').split(': ')
 *** 0164:    return cached_spdx_info[1]
     0165:
     0166:#Find InfoInLicenseFile and fill into PackageLicenseInfoInLicenseFile.
     0167:def find_infoinlicensefile(sstatefile):
     0168:    import subprocess
Exception: IndexError: list index out of range

ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/libpsl/0.21.0-r0/temp/log.do_spdx.17370
ERROR: Task (/home/yocto/output/poky/meta/recipes-support/libpsl/libpsl_0.21.0.bb:do_spdx) failed with exit code '1'
-------------------------------------------------------------------------------------------------

ERROR: adwaita-icon-theme-3.34.3-r0 do_spdx: Could not invoke scancode Command '/home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/recipe-sysroot-native/usr/bin/scancode -lpci --spdx-tv /home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/spdx_sstate_dir/allarch-poky-linux/adwaita-icon-theme-3.34.3-r0/adwaita-icon-theme-3.34.3.spdx /home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/spdx_temp/' returned 1:
b'Setup plugins...\nCollect file inventory...\nScan files for: info, licenses, copyrights, packages with 1 process(es)...\nScanning done.\nSome files failed to scan properly:\nPath: spdx_temp/adwaita-icon-theme-3.34.3/src/fullcolor/legacy/accessories-dictionary.svg\nSummary:        info, licenses, copyrights, packages with 1 process(es)\nErrors count:   1\nScan Speed:     0.88 files/sec. 31.42 KB/sec.\nInitial counts: 3178 resource(s): 3081 file(s) and 97 directorie(s) \nFinal counts:   3178 resource(s): 3081 file(s) and 97 directorie(s) for 107.63 MB\nTimings:\n  scan_start: 2020-06-10T194306.005261\n  scan_end:   2020-06-10T204137.397551\n  setup_scan:licenses: 1.45s\n  setup: 1.45s\n  inventory: 1.16s\n  scan:packages: 0.32s\n  scan: 3507.48s\n  output:spdx-tv: 7.24s\n  output: 7.24s\n  total: 3518.95s\nRemoving temporary files...done.\n'
ERROR: Logfile of failure stored in: /home/yocto/output/build/tmp/work/all-poky-linux/adwaita-icon-theme/3.34.3-r0/temp/log.do_spdx.15064
ERROR: Task (/home/yocto/output/poky/meta/recipes-gnome/gnome/adwaita-icon-theme_3.34.3.bb:do_spdx) failed with exit code '1'
 
```

**Comment by chaithubk** [comment]
Issue logged in fossology
https://github.com/fossology/fossology/issues/1750
